### ISSUE TITLE
Community voting margins should probably only consider recently active users

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#107]
I was thinking about community votes and the two options we had to deal with inactive users: count up the number of positive versus negative votes at the end of the vote and if there are enough positive votes, consider the vote passed; or make the margin a variable number equal to 50%+1 of users active on the site in the last, say, month.

I'm leaning towards the latter because by default not voting in a poll already implies your vote is against, and it models political polling more closely that way (which is just something I like I guess?) I also like the latter method more because it encourages people to be active, I guess. Also it should be easier to code than the former option. But I want to hear your thoughts!

**Comment by toBeOfUse** [comment]
My thoughts hmmm. Maybe I'm wrong, but I feel like not voting can actually
just mean you don't care about a thing either way? Which, to be real, most
people probably wouldn't care too much about non-crazy changes to like
community names or pictures or descriptions, most of that probably won't
actually noticably interfere with the community's general day-to-day user
activity... and so this large bloc of people who probably don't really care
about a change are currently folded into the people who are against it
which I feel like could make things harder to switch up and keep fresh or
just to marginally improve. But I do like the idea of encouraging people to
be active! So that would take effect if there's not only the differently
calculated margin but also you're not eligible to vote unless you've been
active I guess, if there's no eligibility requirement like that I don't
know if people would stay active just out of a vague sense that they're
making vote margin requirements higher. Also I feel like if a significant
number of new people joined the community in the middle of a vote you would
have to change the margin correspondingly or else you could end up in a
situation that feels kind of weird, like if you set the margin and then
halfway through the vote the community like doubles in size?

Obviously the system you are favorimg here is the much more dynamic and
intriguing, and I'm interested to hear anything you would like to say about
political polling models, I have no idea about that, perhaps I'm just the
one here that's much less informed about voting mechanism effects, I grew
up only ever learning about two-party first-past-the-post. My first
instinct is still to add voting against, because it might make it less hard
for votes to succeed because of what I mentioned above and also it feels
more simple and basically harder to argue with the results of? Because
there's no margin figure that could feel kind of fuzzy and based partially
on chance, like it might have been different if the vote had started on a
slightly different day? BUT I'm not going to complain if we do it either
way. Maybe making things slightly fuzzier might feel more natural and more
fitting for anyone who doesn't take random votes too seriously. Basically
idk, and I'm perfectly happy to leave the decision entirely up to you.

**Comment by lowercasename** [comment]
Just quickly, I always thought that the margin should travel and not be fixed to the creation date of the vote, which is indeed how it works now - it’s just calculated on every page load as a simple majority of the current user count, and that number decides whether the current voter is the ‘tipping point’ voter whose vote will activate the change itself.



________________________________

**Comment by lowercasename** [comment]
Fixed in https://github.com/lowercasename/sweet/pull/117/commits/05ce0e93799c52b8f770bb6bd515e4cf8239caf7

Now only members active in the last two weeks count for vote margins (and vote margins change live to always be equal to one more than half of those recently active members). Democracy! Or something!
