### ISSUE TITLE
Various website asset size concerns

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#113]
~It's 1.1mb! And it's not like we're using a large percentage of it I don't think~ Ok, scratch that. fontawesome/js/all.min.js was quite large and was 40% of the size of our payload for the homepage for my test user, and I created this issue to complain about that, but, see next comment.

**Comment by toBeOfUse** [comment]
Well, the compression module knocked it down to 0.4mb (25% of the new total payload) but it still annoys me on principle that we're sending a file with a whole bunch of stuff we don't use. But I don't much feel like combing through and deleting stuff line by line manually. Troubling.

**Comment by toBeOfUse** [comment]
Also, the Google Chrome coverage checker alleges that a full 95.9% of bootstrap.min.css is going unused, although that's a comparatively minor issue (it's only 145 kb). Also, style.css is loading OpenDyslexic3 and OpenDyslexic3-Bold and then not apparently using them anywhere in that file that I can see?

**Comment by lowercasename** [comment]
OpenDyslexic is a font I wanna implement at some point for people who would prefer to use it sitewide. Haven’t got around to it yet. In terms of compression, this should probably be fine because I also gzip on the server and express aggressively caches in production environments, so these files should only ever be downloaded once. I hope!
