### ISSUE TITLE
Link Previews: Redux

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#131]
I think it would be a nice idea to have a little 'add a link!' button which sits next to the 'add a photo' button, which shows a form to add some links, you can add multiple links I guess up to an arbitrary number, fewer than ten billion links, when you post your post they appear as link previews below your post. Maybe when you type in a link and then press Enter or Yes, Please Add This Link He Is A Good Link, the link turns into a link preview box to make it clear that what you are doing is adding a link preview box. Problems with this:

- Videos already auto-preview - maybe links should also auto-preview rather than be added manually, or maybe videos shouldn't auto-preview, or maybe something else?
- @toBeOfUse you were once talking about it being nice if we could add images and links and all in various orders. I guess this would be easyish to do from a UI perspective, we just make an Add an Element Button and those elements could be text, image, or link preview, and the user can rearrange the elements once they're added, but this feels like it would be a major re-write to the backend post storage code, I envision arrays upon arrays and am filled with fears

**Comment by toBeOfUse** [comment]
yeah... what we have for adding embeds is all right for now, but i think it would probably be better to have an "add a video embed preview" button just like and alongside the "add a link!" button that you describe, instead of requiring those to be added as awkwardly placed urls and auto-previewing. and i would like the option to add those and images and text in various orders.

the backend is actually the part of that that would concern me less. the way i see it, the text parts of the post should still be in parsedContent, and then the images and embeds and link previews would just be stored with a "position" field describing where they belong within the post's text, so they could be rendered and then put in there in all their various orders. this is already partially implemented in the most recent pull request, which allows video embeds to be "mixed in" to parsedContent before the post is displayed, so they're still rendered according to the latest version of the embed.handlebars partial but they're placed according to their original positions in the text instead of being always put at the end. the frontend is what gives me pause - i don't really want to break the post form up into multiple quill editor instances, and while quill provides for custom "embed" types that we could use to make our link previews, video embed previews, and images show up within the editor as the user creates their post pretty automatically, letting the user rearrange those things within the text would be the potentially tricky part. i'll investigate.

**Comment by toBeOfUse** [comment]
Actually... the really interesting question is: do we have an "add a link" button and an "add a video embed preview" button, or do we just automatically cause link previews that link to videos to turn into an embedded version of the video when clicked on? I'm going to lean towards just having the "add a link!" button as you describe it, but if it's a url to a video have some text in the resulting preview like "will open as an embedded video" and make it do that. This will prevent people from adding just regular link previews that link to youtube videos without an embed getting involved, but probably they'll get over it???

**Comment by toBeOfUse** [comment]
We could create other kinds of embeds than videos pretty smoothly through intercepting urls in link previews, too, like for Twitter or Tumblr or Instagram I guess! No one really actually uses those kinds of embeds normally, but it might be an interesting way to encourage people to cross-post stuff to sweet, it feels to me slightly less garish than screenshotting your own stuff and posting that

**Comment by lowercasename** [comment]
I think you're right and we should have one 'add a link!' button - and do we then remove the auto link embedder from the text parser? It's certainly easier for us to manage!

**Comment by toBeOfUse** [comment]
Yes, definitely. I've implemented most of this in the front end text editor in the newest new pull request (#130), although I haven't actually made the requisite server changes yet so if you actually try to submit a post or comment lo and behold it will explode in your hands. (also the new usages of class names, id names, function names, variable names, and comments are disastrous and they should probably all be rewritten)

**Comment by lowercasename** [comment]
If I get a chance next week I can do those rewrites,  but for now whatever works is good - this is well above and beyond my initial idea, maybe the best (or at least most straightforward and yet powerful) editor I've seen online.
