### ISSUE TITLE
If I post in a community, the feed goes blank, then is... doubled?

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#138]
First the whole feed goes blank and comes up with no posts, then this happens after a reload:

<img width="702" alt="Screenshot 2019-08-13 at 12 33 34" src="https://user-images.githubusercontent.com/1748384/62938257-a0c5c280-bdc6-11e9-8a2e-d3ba1bfca4fa.png">

(Don't ask questions about my filler content, my testing server's users lead a rich internal life)

**Comment by toBeOfUse** [comment]
See if that still happens. That's a weird one, it only seemed to happen
about half the time, completely arbitrarily, it seems like the infinite
scroll script didn't want to load the next page? Like, when the feed was
coming up blank, that's because the infinite scroll script was making no
request to the server, despite the fact that infiniteScroll("loadNextPage")
was being called. Only on community pages, and only about half the time for
me. But it's arbitrarily changed now, maybe to better match its developers
assumptions about how it was going to be used (it's true that we weren't
really loading the "next" page but come on)

**Comment by toBeOfUse** [comment]
oh, now its just coming up doubled for me, that was happening at all before

**Comment by toBeOfUse** [comment]
Ok so it's fixed I guess bc I turned prefill off and so the infinite scroll script stopped making the request for the exact same posts twice, which is what it was doing. And the reason the feed coming up blank after making a post initially was I guess because that was another prefill situation and it was just deciding to make the same showposts request again and the most recent request was, in the case of your two-posts community, the one where you reached the bottom of the feed and it 404ed. No idea why prefill wasn't running the code in the on append event listener and updating the needPostsOlderThan variable so that it would make an accurate next request, like, that code works fine when it runs because you scrolled down. But while I'm thinking of it some code needs to be added to the very botton of the on append event listener in onPostsLoadScripts to be like "if the document height is not currently actually larger than the window height, do the loadNextPage command." And that combined with the loadNextPage command in restartInfiniteScroll and after startInfiniteScroll will be our non-malfunctioning replacement for prefill, yeehaw.
