### ISSUE TITLE
Boosted posts appear twice

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#18]
I think this is what that entry on the Trello board refers to?
![Screenshot_20190429-214455](https://user-images.githubusercontent.com/49729978/56936940-3499aa00-6ac8-11e9-83e4-782b0f80475a.jpg)

**Comment by lowercasename** [comment]
That’s the bastard. There’s some commented out code in the showposts route I was trying to make work, but it really threw me. Here’s the intended functionality:

- In each block of ten posts that gets loaded (or in a larger set, but I don’t know how one would do that - check each new page based on previous pages, maybe?):
- If a boosted post is shown, hide the original post;
- Unless the original post appears higher than the boosted post (because it’s been commented on), in which case add a line to the top of the post box with a list of the users (maybe only users you follow?) who have boosted that post.

Alternatively, maybe boosted posts should actually adopt the lastUpdated time stamp of their parent, which might semantically make more sense, and in which case really that line should appear whether the post in question is the boosted post or the parent. Basically they should look identical and only appear once in any timeline, irrelevant of how many copies of that post are in the timeline.
